# Change these first
owner: DariusStClair # Your GitHub username
repo: Uptime # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: CDN
    url: https://i.darius.lol
  - name: IMGEN
    url: https://darius.lol/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain 
  cname: status.darius.lol
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Darius' Services Uptime
  introTitle: "**Darius Services**\n"
  introMessage: Below is the current status of various services I'm responsible for (excluding Google, duh).
  navbar:
    - title: Status
      href: /
    - title: CDN
      href: https://i.darius.lol
      icon: https://i.darius.lol/static/icons/cdn.png
    - title: Imgen
      href: https://darius.lol
      icon: https://i.darius.lol/static/icons/imgen.png
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org).

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
